### ISSUE TITLE
Product Roadmap

### ISSUE THREAD

**Issue by SatanshuMishra** [SatanshuMishra/CulinaryCache#2]
The following is the roadmap for creating recipes:
- [ ] Step-by-step on-boarding process. 
- [ ] Ask for recipe name.
- [ ] Ask for ingredients w/ Preparation and Cooking time.
- [ ] Ask for instructions.
- [ ] Cross-check instructions with ingredients list.
- [ ] Ask for Recipe image.
- [ ] Provide Summary of Recipe.
- [ ] Add to database.

The following is the roadmap for viewing recipes:
- [ ] Timer Functionality to track time (Refrigerate for 20m)
- [ ] Cook Counter (Fun Easter Egg)
- [ ] #4

The following is the roadmap for app behaviour:
- [ ] Open multiple instances or windows with multiple recipes.
